# Generated by Django 4.0.5 on 2022-07-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_title_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#00FF00', 'Green'), ('#FF0000', 'Red'), ('#0000FF', 'Blue')], max_length=100),
        ),
    ]
